apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-e9kzha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-e9kzha
  namespace: my-nginx-e9kzha
  labels:
    name: nginx-e9kzha
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-e9kzha
  template:
    metadata:
      namespace: my-nginx-e9kzha
      labels:
        name: nginx-e9kzha
    spec:
      containers:
      - name: nginx-e9kzha
        image: nginx
        ports:
        - containerPort: 80

